export const PAGE_PATH = {
  login: "/login",
  main: "/",
  second: "/second",
  homeEmployee: "/homeemployee",
  orders: "/orders",
  cash: "/cash",
  customers: "/customers",
  homeManager: "/homemanager",
  homeAdmin: "/homeadmin",
  globalOrders: "/globalorders",
  managerReports: "/managerreports",
  employeeManagment: "/employeemanagment",
  branches: "/brances",
  adminReports: "/adminreports",
} as const;
